/**
 * Generated Supabase Database Types
 *
 * This is a minimal stub generated by `supabase gen types typescript`.
 * It provides the basic structure needed for imports in the client/server/admin files.
 * Once connected to a Supabase instance, regenerate this file with:
 *   supabase gen types typescript --project-id <project-id> > database.types.ts
 */

export interface Database {
  public: {
    Tables: Record<string, unknown>
    Views: Record<string, unknown>
    Functions: Record<string, unknown>
    Enums: Record<string, unknown>
    CompositeTypes: Record<string, unknown>
  }
  storage: {
    Tables: Record<string, unknown>
  }
  graphql_public: {
    Tables: Record<string, unknown>
  }
}
